name: unit test
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install lua
        run: |
          cd ${{ github.workspace }}; \
          curl -R -O http://www.lua.org/ftp/lua-5.4.3.tar.gz; \
          tar zxf lua-5.4.3.tar.gz; \
          cd lua-5.4.3; \
          make linux test 
      - name: Run tests  
        run: |
          cd ${{ github.workspace }}/test; \
<<<<<<< HEAD
                    ../lua-5.4.3/src/lua  some.lua; \
          ../lua-5.4.3/src/lua  sample.lua; \
          ../lua-5.4.3/src/lua sym.lua
=======
          ../lua-5.4.3/src/lua -e ''; \
          ../lua-5.4.3/src/lua ok.lua *.lua; 
>>>>>>> 13f675c08180cf9159b1f764e8a9b9f5f033f1d9
      - run: echo "ğŸ This job's status is ${{ job.status }}."

#../lua-5.4.3/src/lua  list.lua; \
#../lua-5.4.3/src/lua num.lua; \
#../lua-5.4.3/src/lua files.lua; \
#../lua-5.4.3/src/lua  rand.lua; \

